services:
  frontend:
    image: maimuna03/mep-frontend:latest
    container_name: mep-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app
    depends_on:
      - backend

  backend:
    # image: maimuna03/mep-backend:latest
    # image muss noch entkommentiert werden -> Es muss so aussehen wie in dev 
    build:
      context: ./backend
      dockerfile: Dockerfile 
    container_name: mep-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Docker-Socket hinzugefügt
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: postgres:16
    container_name: mep-db
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./database/.env
      # POSTGRES_HOST_AUTH_METHOD: trust     #Kein Passwort nötig (nicht nötig, wenn Passwort gesetzt)
    volumes:
      # Speichert die PostgreSQL-Daten persistent außerhalb des Containers → Daten bleiben erhalten, auch wenn der Container neu gestartet oder gelöscht wird
      - postgres_data:/var/lib/postgresql/data
      # Führt einmalig beim allerersten Start das SQL-Initialisierungsskript aus (nicht mehr bei späteren Starts, wenn Daten schon da sind)
      - ./database/schemas/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: