services:
  frontend:
    image: maimuna03/mep-frontend:latest
    container_name: mep-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app
    depends_on:
      - backend

  backend:
    #image: maimuna03/mep-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    container_name: mep-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Docker-Socket hinzugefügt
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://imblue_user:secret@db:5432/imblue_db

  db:
    image: postgres:16
    container_name: mep-db
    restart: always
    environment:
      POSTGRES_DB: imblue_db
      POSTGRES_USER: imblue_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

