server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /app/storage/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: ['localhost']
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
          __docker__: true

  - job_name: fastapi-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: fastapi-logs
          __path__: /app/logs/event.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            source: source
            action: action
            user_id: user_id
            container_id: container_id
            container_name: container_name
            image_id: image_id
            cpu: cpu
            ram: ram
      - drop:
          expression: '.*("start_existing"|"already_running"|"CPU 0.00%"|"RAM 0.00%").*'
